### Sorting and visualizing UniPept lowest common ancestor analyses over diatom degradation experiment

#### Beginning with: LCA peptides in csvs

#### Goal: spectral abundance-corrected (NAAF) algal and bacterial peptide over the 4 timepoints

## Issue: the `join` commands at the end for diatom and bacterial peptides need to be run independently from one another. To do this, run the diatom command, restart the kernal, then run the bacterial.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# read the data into pandas dataframes
tryp_324_DN = pd.read_csv("/home/millieginty/Documents/git-repos/rot-mayer/analyses/unipept/lca/cleaned/T5-324-trypsin-lca-DN.csv")

tryp_324_DN.head(6)

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
0,KFDEETK,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TPEEEER,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HLDVDDSGK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SPNETEER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VVEEVVR,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,DKFDEETK,Candidatus,Cloacimonetes,bacterium,Bacteria,NaN,NaN,NaN,Candidatus,Cloacimonetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Candidatus

In [3]:
# keep only the rows where kingdom = Bacteria

tryp_324_DN_Bac1 = tryp_324_DN.loc[(tryp_324_DN['kingdom'] == 'Bacteria')]

tryp_324_DN_Bac2 = tryp_324_DN.loc[(tryp_324_DN['subkingdom'] == 'Bacteria')]

print('# of kingdom = ', len(tryp_324_DN_Bac1))

print('# of subkingdom = ', len(tryp_324_DN_Bac2))

frames = [tryp_324_DN_Bac1, tryp_324_DN_Bac2]
  
tryp_324_DN_Bac = pd.concat(frames)

print('# of total Bacteria peptides = ', len(tryp_324_DN_Bac))

tryp_324_DN_Bac.head()

# of kingdom =  74
# of subkingdom =  4
# of total Bacteria peptides =  78

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
42,VTNAELAEVLAR,Escherichia,coli,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Escherichia,NaN,NaN,NaN,Escherichia,coli,NaN
77,QGYSNPR,Barnesiella,viscericola,Bacteria,NaN,NaN,NaN,Bacteroidetes,NaN,NaN,...,NaN,NaN,NaN,Barnesiella,NaN,NaN,NaN,Barnesiella,viscericola,NaN
79,FNSSLAGR,Rhodobacter,viridis,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Rhodobacter,NaN,NaN,NaN,Rhodobacter,viridis,NaN
122,WGAPAPR,Halomonas,ilicicola,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Halomonas,NaN,NaN,NaN,Halomonas,ilicicola,NaN
157,ANNDVPR,Candidatus,Aureabacteria,Bacteria,NaN,NaN,NaN,Candidatus,Aureabacteria,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# keep only the rows where phylum = Bacillariophyta

tryp_324_DN_Dia1 = tryp_324_DN.loc[(tryp_324_DN['phylum'] == 'Bacillariophyta')]

tryp_324_DN_Dia2 = tryp_324_DN.loc[(tryp_324_DN['subphylum'] == 'Bacillariophyta')]

print('# of phylum = ', len(tryp_324_DN_Dia1))

print('# of subphylum = ', len(tryp_324_DN_Dia2))

frames = [tryp_324_DN_Dia1, tryp_324_DN_Dia2]
  
tryp_324_DN_Dia = pd.concat(frames)

print('# of total diatom peptides = ', len(tryp_324_DN_Dia))

print('colunm names:', tryp_324_DN_Dia.columns)

tryp_324_DN_Dia.head()

# of phylum =  5
# of subphylum =  7
# of total diatom peptides =  12
colunm names: Index(['peptide', 'lca', 'superkingdom', 'kingdom', 'subkingdom',
       'superphylum', 'phylum', 'subphylum', 'superclass', 'class', 'subclass',
       'infraclass', 'superorder', 'order', 'suborder', 'infraorder',
       'parvorder', 'superfamily', 'family', 'subfamily', 'tribe', 'subtribe',
       'genus', 'subgenus', 'species', 'group', 'species.1', 'subgroup',
       'species.2', 'subspecies'],
      dtype='object')

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
378,CSESPAFTK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,VLGPLMSK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1037,SLPFLTVPEK,Thalassiosirales,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,Coscinodiscophyceae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1152,DVTGEGEFVGDFR,Thalassiosirales,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,Coscinodiscophyceae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1398,CSESPAFTKR,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Now I want to read in the file containing the stripped peptides with NAAF values
####  - NAAF stands for 'noramlized area abunace factor'

### I want to join the dataframes if they share an index (stripped peptide with equated leucine and isoleucines)
#### - That means I'll reindex the processed peptide file

In [5]:
tryp_324_DN_NAAF = pd.read_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T5_324_trypsin_DN_peptides.csv")

tryp_324_DN_NAAF.set_index('stripped_peptide')
tryp_324_DN_NAAF = tryp_324_DN_NAAF.loc[:, ~tryp_324_DN_NAAF.columns.str.contains('^Unnamed')]

tryp_324_DN_NAAF.rename(columns = {'stripped_peptide':'peptide'}, inplace = True)

print('# of total peptides = ', len(tryp_324_DN_NAAF))

print('column names:', tryp_324_DN_NAAF.columns)

tryp_324_DN_NAAF.head()

# of total peptides =  4201
column names: Index(['peptide', 'Area', 'NAAF_num.'], dtype='object')

     peptide       Area      NAAF_num.
0    KFDEETK  1710000.0  244285.714286
1    TPEEEER    52200.0    7457.142857
2  HLDVDDSGK   180000.0   20000.000000
3    TPEEEER    55300.0    7900.000000
4  HLDVDDSGK   232000.0   25777.777778

In [6]:
# get the intersection of the diatom peptides and corresponding peptides w/ NAAFs

over = np.intersect1d(tryp_324_DN_Dia["peptide"], tryp_324_DN_NAAF["peptide"])

print(over)

#print(tryp_324_DN_Dia[tryp_324_DN_NAAF.peptide.isin(over)])

#print(tryp_324_DN_NAAF[tryp_324_DN_Dia.peptide.isin(over)])

['ALQELQHGR' 'CSESPAFTK' 'CSESPAFTKR' 'DVTGEGEFVGDFR' 'EGLGYSLGR'
 'ETLGVSLAR' 'FATYWPR' 'SGNGDPFR' 'SLPFLTVPEK' 'TGATGFGSK' 'VLGPLMSK'
 'VVNAAQEK']

In [ ]:
# join the dataframes if the peptide values are the same using 'join'
# since a couple are de novo only (more for bacteria), we won't have all the UniPept peptides overlap 

tryp_324_DN_Dia.set_index('peptide', inplace=True)
tryp_324_DN_NAAF.set_index('peptide', inplace=True)

tryp_324_DN_Diatoms = tryp_324_DN_Dia.join(tryp_324_DN_NAAF, how='left', rsuffix='_other')


print('# of total diatom peptides = ', len(tryp_324_DN_Diatoms))

tryp_324_DN_Diatoms.head()

In [ ]:
# write to a csv

tryp_324_DN_Diatoms.to_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T5_324_trypsin_DN_NAAF_diatom_peptides.csv")

In [7]:
# join the dataframes if the peptide values are the same using 'join'
# since a couple are de novo only (more for bacteria), we won't have all the UniPept peptides overlap 

tryp_324_DN_Bac.set_index('peptide', inplace=True)
tryp_324_DN_NAAF.set_index('peptide', inplace=True)

tryp_324_DN_Bacteria = tryp_324_DN_Bac.join(tryp_324_DN_NAAF, how='left', rsuffix='_other')


print('# of total Bacteria peptides = ', len(tryp_324_DN_Bacteria))

tryp_324_DN_Bacteria.head()

# of total Bacteria peptides =  113

,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,subclass,...,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies,Area,NAAF_num.
peptide,,,,,,,,,,,,,,,,,,,,,
ACPDEAR,Sorangium,cellulosum,Bacteria,NaN,NaN,NaN,Proteobacteria,delta/epsilon,subdivisions,NaN,...,NaN,NaN,Sorangium,NaN,NaN,NaN,Sorangium,cellulosum,57700.0,8242.857143
AFLGELVTR,Bacillus,wiedmannii,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Bacilli,...,NaN,Bacillus,NaN,Bacillus,cereus,group,NaN,Bacillus,204000.0,22666.666667
AFLGELVTR,Bacillus,wiedmannii,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Bacilli,...,NaN,Bacillus,NaN,Bacillus,cereus,group,NaN,Bacillus,39700.0,4411.111111
AGGTWQEK,Ruminococcaceae,bacterium,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Clostridia,...,NaN,NaN,NaN,NaN,NaN,Ruminococcaceae,bacterium,NaN,85600.0,10700.000000
ALADDLSSK,Campylobacter,concisus,Bacteria,NaN,NaN,NaN,Proteobacteria,delta/epsilon,subdivisions,NaN,...,NaN,NaN,Campylobacter,NaN,NaN,NaN,Campylobacter,concisus,398000.0,44222.222222

In [8]:
# write to a csv

tryp_324_DN_Bacteria.to_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T5_324_trypsin_DN_NAAF_bacteria_peptides.csv")