### Sorting and visualizing UniPept lowest common ancestor analyses over diatom degradation experiment

#### Beginning with: LCA peptides in csvs

#### Goal: spectral abundance-corrected (NAAF) algal and bacterial peptide over the 4 timepoints

## Issue: the `join` commands at the end for diatom and bacterial peptides need to be run independently from one another. To do this, run the diatom command, restart the kernal, then run the bacterial.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# read the data into pandas dataframes
tryp_322_DN = pd.read_csv("/home/millieginty/Documents/git-repos/rot-mayer/analyses/unipept/lca/cleaned/T0-322-trypsin-lca-DN.csv")

tryp_322_DN.head(6)

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
0,TPEEEER,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAEEEEER,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WAEEEEER,Viridiplantae,Eukaryota,Viridiplantae,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KLPEER,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ESQAWSR,Tardiphaga,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,Alphaproteobacteria,...,NaN,NaN,Tardiphaga,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,DNEETK,root,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# keep only the rows where kingdom = Bacteria

tryp_322_DN_Bac1 = tryp_322_DN.loc[(tryp_322_DN['kingdom'] == 'Bacteria')]

tryp_322_DN_Bac2 = tryp_322_DN.loc[(tryp_322_DN['subkingdom'] == 'Bacteria')]

print('# of kingdom = ', len(tryp_322_DN_Bac1))

print('# of subkingdom = ', len(tryp_322_DN_Bac2))

frames = [tryp_322_DN_Bac1, tryp_322_DN_Bac2]
  
tryp_322_DN_Bac = pd.concat(frames)

print('# of total Bacteria peptides = ', len(tryp_322_DN_Bac))

tryp_322_DN_Bac.head()

# of kingdom =  100
# of subkingdom =  5
# of total Bacteria peptides =  105

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
61,FNSSLAGR,Rhodobacter,viridis,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Rhodobacter,NaN,NaN,NaN,Rhodobacter,viridis,NaN
68,WTLEEDAK,Kutzneria,buriramensis,Bacteria,NaN,NaN,NaN,Actinobacteria,NaN,NaN,...,NaN,NaN,NaN,Kutzneria,NaN,NaN,NaN,Kutzneria,buriramensis,NaN
105,VTNAELAEVLAR,Escherichia,coli,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Escherichia,NaN,NaN,NaN,Escherichia,coli,NaN
108,QGYSNPR,Barnesiella,viscericola,Bacteria,NaN,NaN,NaN,Bacteroidetes,NaN,NaN,...,NaN,NaN,NaN,Barnesiella,NaN,NaN,NaN,Barnesiella,viscericola,NaN
137,VSLNKVYK,Ehrlichia,minasensis,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,...,NaN,NaN,NaN,Ehrlichia,NaN,canis,group,NaN,Ehrlichia,minasensis

In [4]:
# keep only the rows where phylum = Bacteria

tryp_322_DN_Dia1 = tryp_322_DN.loc[(tryp_322_DN['phylum'] == 'Bacillariophyta')]

tryp_322_DN_Dia2 = tryp_322_DN.loc[(tryp_322_DN['subphylum'] == 'Bacillariophyta')]

print('# of phylum = ', len(tryp_322_DN_Dia1))

print('# of subphylum = ', len(tryp_322_DN_Dia2))

frames = [tryp_322_DN_Dia1, tryp_322_DN_Dia2]
  
tryp_322_DN_Dia = pd.concat(frames)

print('# of total diatom peptides = ', len(tryp_322_DN_Dia))

print('colunm names:', tryp_322_DN_Dia.columns)

tryp_322_DN_Dia.head()

# of phylum =  7
# of subphylum =  8
# of total diatom peptides =  15
colunm names: Index(['peptide', 'lca', 'superkingdom', 'kingdom', 'subkingdom',
       'superphylum', 'phylum', 'subphylum', 'superclass', 'class', 'subclass',
       'infraclass', 'superorder', 'order', 'suborder', 'infraorder',
       'parvorder', 'superfamily', 'family', 'subfamily', 'tribe', 'subtribe',
       'genus', 'subgenus', 'species', 'group', 'species.1', 'subgroup',
       'species.2', 'subspecies'],
      dtype='object')

,peptide,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,...,tribe,subtribe,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies
339,CSESPAFTKR,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,VLGPLMSK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,NGFLDFGWDK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
588,CSESPAFTK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,QVSYAMAK,Bacillariophyta,Eukaryota,NaN,NaN,NaN,Bacillariophyta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Now I want to read in the file containing the stripped peptides with NAAF values
####  - NAAF stands for 'noramlized area abunace factor'

### I want to join the dataframes if they share an index (stripped peptide with equated leucine and isoleucines)
#### - That means I'll reindex the processed peptide file

In [5]:
tryp_322_DN_NAAF = pd.read_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T0_322_trypsin_DN_peptides.csv")

tryp_322_DN_NAAF.set_index('stripped_peptide')
tryp_322_DN_NAAF = tryp_322_DN_NAAF.loc[:, ~tryp_322_DN_NAAF.columns.str.contains('^Unnamed')]

tryp_322_DN_NAAF.rename(columns = {'stripped_peptide':'peptide'}, inplace = True)

print('# of total peptides = ', len(tryp_322_DN_NAAF))

print('column names:', tryp_322_DN_NAAF.columns)

tryp_322_DN_NAAF.head()

# of total peptides =  5912
column names: Index(['peptide', 'Area', 'NAAF_num.'], dtype='object')

    peptide      Area     NAAF_num.
0   TPEEEER  156000.0  22285.714286
1   TPEEEER  171000.0  24428.571429
2  AAEEEEER   26400.0   3300.000000
3  WAEEEEER   43100.0   5387.500000
4   TPEEEER  128000.0  18285.714286

In [6]:
# get the intersection of the diatom peptides and corresponding peptides w/ NAAFs

over = np.intersect1d(tryp_322_DN_Dia["peptide"], tryp_322_DN_NAAF["peptide"])

print(over)

#print(tryp_322_DN_Dia[tryp_322_DN_NAAF.peptide.isin(over)])

#print(tryp_322_DN_NAAF[tryp_322_DN_Dia.peptide.isin(over)])

['ALDFGWDK' 'ALQELQHGR' 'ATMEEVYK' 'CSESPAFTK' 'CSESPAFTKR'
 'DVPGTGNEFVGDFR' 'ESHPLTYK' 'ETLGVSLAR' 'FATYWPR' 'NGFLDFGWDK' 'QVSYAMAK'
 'SGNGDPFR' 'SGSDVWR' 'SNEETLAWLR' 'VLGPLMSK']

In [ ]:
# join the dataframes if the peptide values are the same using 'join'
# since a couple are de novo only (more for bacteria), we won't have all the UniPept peptides overlap 

tryp_322_DN_Dia.set_index('peptide', inplace=True)
tryp_322_DN_NAAF.set_index('peptide', inplace=True)

tryp_322_DN_Diatoms = tryp_322_DN_Dia.join(tryp_322_DN_NAAF, how='left', rsuffix='_other')


print('# of total diatom peptides = ', len(tryp_322_DN_Diatoms))

tryp_322_DN_Diatoms.head()

In [ ]:
# write to a csv

tryp_322_DN_Diatoms.to_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T0_322_trypsin_DN_NAAF_diatom_peptides.csv")

In [7]:
# join the dataframes if the peptide values are the same using 'join'
# since a couple are de novo only (more for bacteria), we won't have all the UniPept peptides overlap 

tryp_322_DN_Bac.set_index('peptide', inplace=True)
tryp_322_DN_NAAF.set_index('peptide', inplace=True)

tryp_322_DN_Bacteria = tryp_322_DN_Bac.join(tryp_322_DN_NAAF, how='left', rsuffix='_other')


print('# of total Bacteria peptides = ', len(tryp_322_DN_Bacteria))

tryp_322_DN_Bacteria.head()

# of total Bacteria peptides =  164

,lca,superkingdom,kingdom,subkingdom,superphylum,phylum,subphylum,superclass,class,subclass,...,genus,subgenus,species,group,species.1,subgroup,species.2,subspecies,Area,NAAF_num.
peptide,,,,,,,,,,,,,,,,,,,,,
ALTLDSPK,Anaerocolumna,xylanovorans,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Clostridia,...,NaN,Anaerocolumna,NaN,NaN,NaN,Anaerocolumna,xylanovorans,NaN,25300.0,3162.5
DDPEAAKR,Desulfotomaculum,putei,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Clostridia,...,NaN,Desulfotomaculum,NaN,NaN,NaN,Desulfotomaculum,putei,NaN,103000.0,12875.0
DDPEAAKR,Desulfotomaculum,putei,Bacteria,NaN,NaN,NaN,Firmicutes,NaN,NaN,Clostridia,...,NaN,Desulfotomaculum,NaN,NaN,NaN,Desulfotomaculum,putei,NaN,59700.0,7462.5
DFALATELK,Ruegeria,marisrubri,Bacteria,NaN,NaN,NaN,Proteobacteria,NaN,NaN,Alphaproteobacteria,...,NaN,Ruegeria,NaN,NaN,NaN,Ruegeria,marisrubri,NaN,NaN,NaN
DKFDEETK,Candidatus,Cloacimonetes,bacterium,Bacteria,NaN,NaN,NaN,Candidatus,Cloacimonetes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Candidatus,NaN,NaN

In [8]:
# write to a csv

tryp_322_DN_Bacteria.to_csv("/home/millieginty/Documents/git-repos/rot-mayer/data/processed/I-L_NAAFs/T0_322_trypsin_DN_NAAF_bacteria_peptides.csv")